spring.application.name=ecommerce-project
server.port=8090

# MySQL კავშირი
spring.datasource.url=jdbc:mysql://localhost:3306/ecommerce_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=Dafrinteza1!
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.mail.username=pputeici@gmail.com
spring.mail.password=ksrxkykzfswdresb

cloudinary.cloud_name=gpl1zpeq
cloudinary.api_key=551323253533521
cloudinary.api_secret=8mXK_ObqU1jpHzfTQwJu2kPkZUw

# Hibernate და Dialect
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


stripe.secret.key=sk_test_51TquhZAUvEg0KviWaSIEVWS2Y89uV5RRIYwQnCwTbqVNPEcgXCnGBnH9lUOPITT2RftkyPfpTHhedhOXaHM9KZuN00BQ8zUxLL