spring.application.name=ecommerce-project
server.port=8090
spring.datasource.url=jdbc:postgresql://ep-delicate-block-aupfp44s-pooler.c-10.us-east-1.aws.neon.tech/neondb?sslmode=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_Co1tz9QarFVb
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
stripe.secret.key=${STRIPE_SECRET_KEY}


